version: "3.3"

services:
  foreman:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      FOREMAN_DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "80:80"
      - "443:443"
      - "8140:8140"
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./config/foreman:/etc/foreman
      - ./config/foreman-installer:/etc/foreman-installer
      - ./config/foreman-proxy:/etc/foreman-proxy
      - ./logs/foreman:/var/log/foreman
      - ./logs/foreman-installer:/var/log/foreman-installer
      - ./logs/foreman-proxy:/var/log/foreman-proxy
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    depends_on:
      - postgres
    domainname: sf.lan
    hostname: foreman
    restart: "always"

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: foreman
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: foreman
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: "always"

