version: "3.3"

services:
  foreman:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      FOREMAN_DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./config/foreman:/etc/foreman
      - ./config/foreman-installer:/etc/foreman-installer
      - ./config/foreman-proxy:/etc/foreman-proxy
      - ./logs/foreman:/var/log/foreman
      - ./logs/foreman-installer:/var/log/foreman-installer
      - ./logs/foreman-proxy:/var/log/foreman-proxy
    depends_on:
      - postgres
    domainname: sf.lan
    hostname: foreman

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: foreman
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: foreman
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: "always"

