---
foreman:
  foreman_url: https://foreman.docker.lan/
  servername: foreman.docker.lan
  serveraliases:
  - foreman
  custom_repo: true
  db_manage: true
  db_type: postgresql
  db_adapter:
  db_host:
  db_port:
  db_database:
  db_username: foreman
  db_password: 
  db_sslmode:
  - puppet
foreman::plugin::docker: true
foreman::plugin::setup: {}
puppet:
  server: true
foreman_proxy: true
