---
foreman:
  foreman_url: https://foreman.docker.lan/
  servername: foreman.docker.lan
  serveraliases:
  - foreman
  custom_repo: true
  db_manage: false
  db_type: postgresql
  db_host: postgres
  db_database: foreman
  db_username: foreman
  db_password: 
foreman::plugin::docker: true
foreman::plugin::setup: {}
puppet:
  server: true
foreman_proxy: true
